services:
  # Production version
  gotpop-blog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - STORYBLOK_ACCESS_TOKEN=${STORYBLOK_ACCESS_TOKEN}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    container_name: gotpop-blog

  # Development version
  gotpop-blog-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
    container_name: gotpop-blog-dev
    profiles:
      - dev
