# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
      statuses: write

    environment:
      name: EC2 (production)
      url: https://gotpop.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: EC2 (production)

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/gotpop-blog
            git pull origin master
            docker stop gotpop-blog || true
            docker rm gotpop-blog || true
            docker build -t gotpop-blog .
            docker run -d \
              -p 3000:3000 \
              --name gotpop-blog \
              --restart unless-stopped \
              --env-file .env \
              gotpop-blog
            docker image prune -f
            echo "Deployment completed successfully!"
            docker ps
            docker logs gotpop-blog --tail 20

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: EC2 (production)
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://gotpop.io
