# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint and Format

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run format check
        run: yarn format:check
